### ISSUE TITLE
Underline below partner logos is offset on the About Us page (IE11)

### ISSUE THREAD

**Issue by wipro-zara** [buildit/gravity-ui-sass#121]
The partner logos on the About us page are offset to the underline that is below them in the IE11 browser.

**To reproduce bug, follow these steps:**
1. Start IE11
2. Paste "http://www-beta.buildit.digital/about/" into the address bar
3. Scroll to the bottom of the page where the partner logos are displayed

**Expected outcome:**
The partner logos to appear with an underline beneath with an appropriate/no gap between them.

**Actual outcome:**
A large gap between the partner logos and the underline.

**Comment by c1rrus** [comment]
@wipro-zara Is this bug still relevant, considering the work that you and @jimmyj-wipro are doing to redesign the partner logo links? (Btw, is that being done here or on the website? Ideally, it ought to be done here)

If this bug is now redundant (or about to be), we can go ahead and add the "Won't Fix" label and close it.

**Comment by jimmyj-wipro** [comment]
@c1rrus here's the boxed versions [wip](https://github.com/buildit/buildit/tree/WEB-251-styling-of-partner-links), if we're gonna go for this.

**Comment by wipro-zara** [comment]
Solved with branch WEB-251-styling-of-partner-links
